spring:
  application:
    name: weaver
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
  cloudinary:
    name: ${CLOUDINARY_NAME:123}
    api-key: ${CLOUDINARY_API:123}
    secret-key: ${CLOUDINARY_SECRET:123}

  mail:
    host: smtp.gmail.com
    port: 587
    username: huyquoc261223@gmail.com
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

#  kafka:
#    bootstrap-servers: localhost:9092
#
#    producer:
#      retries: 3
#      properties:
#        enable.idempotence: true
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#
#    consumer:
#      group-id: weaver-group
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  web-url: ${WEB_URL}
  server-url: ${SERVER_URL}

jwt:
  secret: ${SECRET}
#  access-token-expiration: 600000     # 10 minutes
#  refresh-token-expiration: 604800000  # 7 days

server:
  port: ${PORT:8090}
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.apache.kafka: WARN
    org.springframework.kafka: WARN