spring:
  application:
    name: weaver

  datasource:
    url: jdbc:postgresql://localhost:5432/weaver
    username: postgres
    password: sondang2906
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  mail:
    host: smtp.gmail.com
    port: 587
    username: huyquoc261223@gmail.com
    password: ${EMAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  web-url: ${WEB_URL}

jwt:
  secret: ${SECRET}
#  access-token-expiration: 600000     # 10 minutes
#  refresh-token-expiration: 604800000  # 7 days

server:
  port: 8090
  error:
    include-message: always
    include-stacktrace: always

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG